const mongoose = require('mongoose');
var elasticsearch = require('elasticsearch');
const config = require('config');
const logger = require("../middleware/logger");


module.exports.connect = () => {
    //connecting database
    //For resolving unexpected warning generated by Mongoose
    mongoose.set('useUnifiedTopology', true);
    mongoose.set('useNewUrlParser', true);

    //connect to localhost mongo database
    mongoose.connect('mongodb://'+config.get('mongoUrl')+'/'+config.get('database'), { useNewUrlParser: true })
    //connect to remote database. Here i'm using https://cloud.mongodb.com/
    //mongoose.connect('mongodb+srv://'+config.get('app_dbuser')+':'+config.get('app_dbpassword')+'@cluster0-pvsgo.mongodb.net/'+config.get('database')+'?retryWrites=true&w=majority',{ useNewUrlParser: true })
    .then(() => {
        console.log("Successful db connection");
    })
    .catch(err => { 
        logger.dbErrorLog(err);
        console.log("Unable to connect..") 
    })
}


module.exports.integrationTestConnect = () => {
    //connecting database
    //For resolving unexpected warning generated by Mongoose
    mongoose.set('useUnifiedTopology', true);
    mongoose.set('useNewUrlParser', true);

    //connect to localhost mongo database
    mongoose.connect('mongodb://'+config.get('TEST_mongoUrl')+'/'+config.get('TEST_database'), { useNewUrlParser: true })
    //connect to remote database. Here i'm using https://cloud.mongodb.com/
    //mongoose.connect('mongodb+srv://'+config.get('app_dbuser')+':'+config.get('app_dbpassword')+'@cluster0-pvsgo.mongodb.net/'+config.get('database')+'?retryWrites=true&w=majority',{ useNewUrlParser: true })
    .then(() => {
        console.log("Successful Test DB connection");
    })
    .catch(err => { 
        logger.dbErrorLog(err);
        console.log("Unable to connect..") 
    })
}



